// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: finops/v1/finops.proto

package finopsv1

import (
	protoreflect "olympus.fleet/00SDLC/Olympus2/40000-Communication-Contracts/430-Protocol-Definitions/000-gen/google/protobuf"
	protoimpl "olympus.fleet/00SDLC/Olympus2/40000-Communication-Contracts/430-Protocol-Definitions/000-gen/google/protobuf"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ValidateBudgetRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ProjectId       string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	RequestedAmount float64                `protobuf:"fixed64,2,opt,name=requested_amount,json=requestedAmount,proto3" json:"requested_amount,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ValidateBudgetRequest) Reset() {
	*x = ValidateBudgetRequest{}
	mi := &file_finops_v1_finops_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateBudgetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateBudgetRequest) ProtoMessage() {}

func (x *ValidateBudgetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_finops_v1_finops_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateBudgetRequest.ProtoReflect.Descriptor instead.
func (*ValidateBudgetRequest) Descriptor() ([]byte, []int) {
	return file_finops_v1_finops_proto_rawDescGZIP(), []int{0}
}

func (x *ValidateBudgetRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *ValidateBudgetRequest) GetRequestedAmount() float64 {
	if x != nil {
		return x.RequestedAmount
	}
	return 0
}

type ValidateBudgetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Approved      bool                   `protobuf:"varint,1,opt,name=approved,proto3" json:"approved,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateBudgetResponse) Reset() {
	*x = ValidateBudgetResponse{}
	mi := &file_finops_v1_finops_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateBudgetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateBudgetResponse) ProtoMessage() {}

func (x *ValidateBudgetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_finops_v1_finops_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateBudgetResponse.ProtoReflect.Descriptor instead.
func (*ValidateBudgetResponse) Descriptor() ([]byte, []int) {
	return file_finops_v1_finops_proto_rawDescGZIP(), []int{1}
}

func (x *ValidateBudgetResponse) GetApproved() bool {
	if x != nil {
		return x.Approved
	}
	return false
}

func (x *ValidateBudgetResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type EstimateCostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Service       string                 `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	Action        string                 `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	Parameters    map[string]string      `protobuf:"bytes,3,rep,name=parameters,proto3" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EstimateCostRequest) Reset() {
	*x = EstimateCostRequest{}
	mi := &file_finops_v1_finops_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EstimateCostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EstimateCostRequest) ProtoMessage() {}

func (x *EstimateCostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_finops_v1_finops_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EstimateCostRequest.ProtoReflect.Descriptor instead.
func (*EstimateCostRequest) Descriptor() ([]byte, []int) {
	return file_finops_v1_finops_proto_rawDescGZIP(), []int{2}
}

func (x *EstimateCostRequest) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *EstimateCostRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *EstimateCostRequest) GetParameters() map[string]string {
	if x != nil {
		return x.Parameters
	}
	return nil
}

type EstimateCostResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EstimatedCost float64                `protobuf:"fixed64,1,opt,name=estimated_cost,json=estimatedCost,proto3" json:"estimated_cost,omitempty"`
	EstimatedUsd  float64                `protobuf:"fixed64,2,opt,name=estimated_usd,json=estimatedUsd,proto3" json:"estimated_usd,omitempty"`
	Confidence    string                 `protobuf:"bytes,3,opt,name=confidence,proto3" json:"confidence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EstimateCostResponse) Reset() {
	*x = EstimateCostResponse{}
	mi := &file_finops_v1_finops_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EstimateCostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EstimateCostResponse) ProtoMessage() {}

func (x *EstimateCostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_finops_v1_finops_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EstimateCostResponse.ProtoReflect.Descriptor instead.
func (*EstimateCostResponse) Descriptor() ([]byte, []int) {
	return file_finops_v1_finops_proto_rawDescGZIP(), []int{3}
}

func (x *EstimateCostResponse) GetEstimatedCost() float64 {
	if x != nil {
		return x.EstimatedCost
	}
	return 0
}

func (x *EstimateCostResponse) GetEstimatedUsd() float64 {
	if x != nil {
		return x.EstimatedUsd
	}
	return 0
}

func (x *EstimateCostResponse) GetConfidence() string {
	if x != nil {
		return x.Confidence
	}
	return ""
}

type TrackUsageRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Service          string                 `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	ResourceId       string                 `protobuf:"bytes,2,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	ConsumptionUnits float64                `protobuf:"fixed64,3,opt,name=consumption_units,json=consumptionUnits,proto3" json:"consumption_units,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TrackUsageRequest) Reset() {
	*x = TrackUsageRequest{}
	mi := &file_finops_v1_finops_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrackUsageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackUsageRequest) ProtoMessage() {}

func (x *TrackUsageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_finops_v1_finops_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackUsageRequest.ProtoReflect.Descriptor instead.
func (*TrackUsageRequest) Descriptor() ([]byte, []int) {
	return file_finops_v1_finops_proto_rawDescGZIP(), []int{4}
}

func (x *TrackUsageRequest) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *TrackUsageRequest) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

func (x *TrackUsageRequest) GetConsumptionUnits() float64 {
	if x != nil {
		return x.ConsumptionUnits
	}
	return 0
}

type TrackUsageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CurrentMtdUsd float64                `protobuf:"fixed64,1,opt,name=current_mtd_usd,json=currentMtdUsd,proto3" json:"current_mtd_usd,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrackUsageResponse) Reset() {
	*x = TrackUsageResponse{}
	mi := &file_finops_v1_finops_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrackUsageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackUsageResponse) ProtoMessage() {}

func (x *TrackUsageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_finops_v1_finops_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackUsageResponse.ProtoReflect.Descriptor instead.
func (*TrackUsageResponse) Descriptor() ([]byte, []int) {
	return file_finops_v1_finops_proto_rawDescGZIP(), []int{5}
}

func (x *TrackUsageResponse) GetCurrentMtdUsd() float64 {
	if x != nil {
		return x.CurrentMtdUsd
	}
	return 0
}

var File_finops_v1_finops_proto protoreflect.FileDescriptor

const file_finops_v1_finops_proto_rawDesc = "" +
	"\n" +
	"\x16finops/v1/finops.proto\x12\tfinops.v1\"a\n" +
	"\x15ValidateBudgetRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12)\n" +
	"\x10requested_amount\x18\x02 \x01(\x01R\x0frequestedAmount\"N\n" +
	"\x16ValidateBudgetResponse\x12\x1a\n" +
	"\bapproved\x18\x01 \x01(\bR\bapproved\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xd6\x01\n" +
	"\x13EstimateCostRequest\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\x12\x16\n" +
	"\x06action\x18\x02 \x01(\tR\x06action\x12N\n" +
	"\n" +
	"parameters\x18\x03 \x03(\v2..finops.v1.EstimateCostRequest.ParametersEntryR\n" +
	"parameters\x1a=\n" +
	"\x0fParametersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x82\x01\n" +
	"\x14EstimateCostResponse\x12%\n" +
	"\x0eestimated_cost\x18\x01 \x01(\x01R\restimatedCost\x12#\n" +
	"\restimated_usd\x18\x02 \x01(\x01R\festimatedUsd\x12\x1e\n" +
	"\n" +
	"confidence\x18\x03 \x01(\tR\n" +
	"confidence\"{\n" +
	"\x11TrackUsageRequest\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\x12\x1f\n" +
	"\vresource_id\x18\x02 \x01(\tR\n" +
	"resourceId\x12+\n" +
	"\x11consumption_units\x18\x03 \x01(\x01R\x10consumptionUnits\"<\n" +
	"\x12TrackUsageResponse\x12&\n" +
	"\x0fcurrent_mtd_usd\x18\x01 \x01(\x01R\rcurrentMtdUsd2\x82\x02\n" +
	"\rFinOpsService\x12U\n" +
	"\x0eValidateBudget\x12 .finops.v1.ValidateBudgetRequest\x1a!.finops.v1.ValidateBudgetResponse\x12O\n" +
	"\fEstimateCost\x12\x1e.finops.v1.EstimateCostRequest\x1a\x1f.finops.v1.EstimateCostResponse\x12I\n" +
	"\n" +
	"TrackUsage\x12\x1c.finops.v1.TrackUsageRequest\x1a\x1d.finops.v1.TrackUsageResponseBeZcOlympusGCP-FinOps/gen/v1/finops;finopsv1b\x06proto3"

var (
	file_finops_v1_finops_proto_rawDescOnce sync.Once
	file_finops_v1_finops_proto_rawDescData []byte
)

func file_finops_v1_finops_proto_rawDescGZIP() []byte {
	file_finops_v1_finops_proto_rawDescOnce.Do(func() {
		file_finops_v1_finops_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_finops_v1_finops_proto_rawDesc), len(file_finops_v1_finops_proto_rawDesc)))
	})
	return file_finops_v1_finops_proto_rawDescData
}

var file_finops_v1_finops_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_finops_v1_finops_proto_goTypes = []any{
	(*ValidateBudgetRequest)(nil),  // 0: finops.v1.ValidateBudgetRequest
	(*ValidateBudgetResponse)(nil), // 1: finops.v1.ValidateBudgetResponse
	(*EstimateCostRequest)(nil),    // 2: finops.v1.EstimateCostRequest
	(*EstimateCostResponse)(nil),   // 3: finops.v1.EstimateCostResponse
	(*TrackUsageRequest)(nil),      // 4: finops.v1.TrackUsageRequest
	(*TrackUsageResponse)(nil),     // 5: finops.v1.TrackUsageResponse
	nil,                            // 6: finops.v1.EstimateCostRequest.ParametersEntry
}
var file_finops_v1_finops_proto_depIdxs = []int32{
	6, // 0: finops.v1.EstimateCostRequest.parameters:type_name -> finops.v1.EstimateCostRequest.ParametersEntry
	0, // 1: finops.v1.FinOpsService.ValidateBudget:input_type -> finops.v1.ValidateBudgetRequest
	2, // 2: finops.v1.FinOpsService.EstimateCost:input_type -> finops.v1.EstimateCostRequest
	4, // 3: finops.v1.FinOpsService.TrackUsage:input_type -> finops.v1.TrackUsageRequest
	1, // 4: finops.v1.FinOpsService.ValidateBudget:output_type -> finops.v1.ValidateBudgetResponse
	3, // 5: finops.v1.FinOpsService.EstimateCost:output_type -> finops.v1.EstimateCostResponse
	5, // 6: finops.v1.FinOpsService.TrackUsage:output_type -> finops.v1.TrackUsageResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_finops_v1_finops_proto_init() }
func file_finops_v1_finops_proto_init() {
	if File_finops_v1_finops_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_finops_v1_finops_proto_rawDesc), len(file_finops_v1_finops_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_finops_v1_finops_proto_goTypes,
		DependencyIndexes: file_finops_v1_finops_proto_depIdxs,
		MessageInfos:      file_finops_v1_finops_proto_msgTypes,
	}.Build()
	File_finops_v1_finops_proto = out.File
	file_finops_v1_finops_proto_goTypes = nil
	file_finops_v1_finops_proto_depIdxs = nil
}
