// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: olympus/finops/v1/finops.proto

package finopsv1connect

import (
	v1 "OlympusGCP-FinOps/40000-Communication-Contracts/430-Protocol-Definitions/000-gen/finops/v1"
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// FinOpsServiceName is the fully-qualified name of the FinOpsService service.
	FinOpsServiceName = "olympus.finops.v1.FinOpsService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// FinOpsServiceEstimateCostProcedure is the fully-qualified name of the FinOpsService's
	// EstimateCost RPC.
	FinOpsServiceEstimateCostProcedure = "/olympus.finops.v1.FinOpsService/EstimateCost"
	// FinOpsServiceValidateBudgetProcedure is the fully-qualified name of the FinOpsService's
	// ValidateBudget RPC.
	FinOpsServiceValidateBudgetProcedure = "/olympus.finops.v1.FinOpsService/ValidateBudget"
	// FinOpsServiceTrackUsageProcedure is the fully-qualified name of the FinOpsService's TrackUsage
	// RPC.
	FinOpsServiceTrackUsageProcedure = "/olympus.finops.v1.FinOpsService/TrackUsage"
)

// FinOpsServiceClient is a client for the olympus.finops.v1.FinOpsService service.
type FinOpsServiceClient interface {
	// Cloud Billing & Usage Intent
	EstimateCost(context.Context, *connect.Request[v1.EstimateCostRequest]) (*connect.Response[v1.EstimateCostResponse], error)
	ValidateBudget(context.Context, *connect.Request[v1.ValidateBudgetRequest]) (*connect.Response[v1.ValidateBudgetResponse], error)
	TrackUsage(context.Context, *connect.Request[v1.TrackUsageRequest]) (*connect.Response[v1.TrackUsageResponse], error)
}

// NewFinOpsServiceClient constructs a client for the olympus.finops.v1.FinOpsService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewFinOpsServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) FinOpsServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	finOpsServiceMethods := v1.File_olympus_finops_v1_finops_proto.Services().ByName("FinOpsService").Methods()
	return &finOpsServiceClient{
		estimateCost: connect.NewClient[v1.EstimateCostRequest, v1.EstimateCostResponse](
			httpClient,
			baseURL+FinOpsServiceEstimateCostProcedure,
			connect.WithSchema(finOpsServiceMethods.ByName("EstimateCost")),
			connect.WithClientOptions(opts...),
		),
		validateBudget: connect.NewClient[v1.ValidateBudgetRequest, v1.ValidateBudgetResponse](
			httpClient,
			baseURL+FinOpsServiceValidateBudgetProcedure,
			connect.WithSchema(finOpsServiceMethods.ByName("ValidateBudget")),
			connect.WithClientOptions(opts...),
		),
		trackUsage: connect.NewClient[v1.TrackUsageRequest, v1.TrackUsageResponse](
			httpClient,
			baseURL+FinOpsServiceTrackUsageProcedure,
			connect.WithSchema(finOpsServiceMethods.ByName("TrackUsage")),
			connect.WithClientOptions(opts...),
		),
	}
}

// finOpsServiceClient implements FinOpsServiceClient.
type finOpsServiceClient struct {
	estimateCost   *connect.Client[v1.EstimateCostRequest, v1.EstimateCostResponse]
	validateBudget *connect.Client[v1.ValidateBudgetRequest, v1.ValidateBudgetResponse]
	trackUsage     *connect.Client[v1.TrackUsageRequest, v1.TrackUsageResponse]
}

// EstimateCost calls olympus.finops.v1.FinOpsService.EstimateCost.
func (c *finOpsServiceClient) EstimateCost(ctx context.Context, req *connect.Request[v1.EstimateCostRequest]) (*connect.Response[v1.EstimateCostResponse], error) {
	return c.estimateCost.CallUnary(ctx, req)
}

// ValidateBudget calls olympus.finops.v1.FinOpsService.ValidateBudget.
func (c *finOpsServiceClient) ValidateBudget(ctx context.Context, req *connect.Request[v1.ValidateBudgetRequest]) (*connect.Response[v1.ValidateBudgetResponse], error) {
	return c.validateBudget.CallUnary(ctx, req)
}

// TrackUsage calls olympus.finops.v1.FinOpsService.TrackUsage.
func (c *finOpsServiceClient) TrackUsage(ctx context.Context, req *connect.Request[v1.TrackUsageRequest]) (*connect.Response[v1.TrackUsageResponse], error) {
	return c.trackUsage.CallUnary(ctx, req)
}

// FinOpsServiceHandler is an implementation of the olympus.finops.v1.FinOpsService service.
type FinOpsServiceHandler interface {
	// Cloud Billing & Usage Intent
	EstimateCost(context.Context, *connect.Request[v1.EstimateCostRequest]) (*connect.Response[v1.EstimateCostResponse], error)
	ValidateBudget(context.Context, *connect.Request[v1.ValidateBudgetRequest]) (*connect.Response[v1.ValidateBudgetResponse], error)
	TrackUsage(context.Context, *connect.Request[v1.TrackUsageRequest]) (*connect.Response[v1.TrackUsageResponse], error)
}

// NewFinOpsServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewFinOpsServiceHandler(svc FinOpsServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	finOpsServiceMethods := v1.File_olympus_finops_v1_finops_proto.Services().ByName("FinOpsService").Methods()
	finOpsServiceEstimateCostHandler := connect.NewUnaryHandler(
		FinOpsServiceEstimateCostProcedure,
		svc.EstimateCost,
		connect.WithSchema(finOpsServiceMethods.ByName("EstimateCost")),
		connect.WithHandlerOptions(opts...),
	)
	finOpsServiceValidateBudgetHandler := connect.NewUnaryHandler(
		FinOpsServiceValidateBudgetProcedure,
		svc.ValidateBudget,
		connect.WithSchema(finOpsServiceMethods.ByName("ValidateBudget")),
		connect.WithHandlerOptions(opts...),
	)
	finOpsServiceTrackUsageHandler := connect.NewUnaryHandler(
		FinOpsServiceTrackUsageProcedure,
		svc.TrackUsage,
		connect.WithSchema(finOpsServiceMethods.ByName("TrackUsage")),
		connect.WithHandlerOptions(opts...),
	)
	return "/olympus.finops.v1.FinOpsService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case FinOpsServiceEstimateCostProcedure:
			finOpsServiceEstimateCostHandler.ServeHTTP(w, r)
		case FinOpsServiceValidateBudgetProcedure:
			finOpsServiceValidateBudgetHandler.ServeHTTP(w, r)
		case FinOpsServiceTrackUsageProcedure:
			finOpsServiceTrackUsageHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedFinOpsServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedFinOpsServiceHandler struct{}

func (UnimplementedFinOpsServiceHandler) EstimateCost(context.Context, *connect.Request[v1.EstimateCostRequest]) (*connect.Response[v1.EstimateCostResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("olympus.finops.v1.FinOpsService.EstimateCost is not implemented"))
}

func (UnimplementedFinOpsServiceHandler) ValidateBudget(context.Context, *connect.Request[v1.ValidateBudgetRequest]) (*connect.Response[v1.ValidateBudgetResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("olympus.finops.v1.FinOpsService.ValidateBudget is not implemented"))
}

func (UnimplementedFinOpsServiceHandler) TrackUsage(context.Context, *connect.Request[v1.TrackUsageRequest]) (*connect.Response[v1.TrackUsageResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("olympus.finops.v1.FinOpsService.TrackUsage is not implemented"))
}
