// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: olympus/finops/v1/finops.proto

package finopsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EstimateCostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Service       string                 `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	Action        string                 `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	Parameters    map[string]string      `protobuf:"bytes,3,rep,name=parameters,proto3" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EstimateCostRequest) Reset() {
	*x = EstimateCostRequest{}
	mi := &file_olympus_finops_v1_finops_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EstimateCostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EstimateCostRequest) ProtoMessage() {}

func (x *EstimateCostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_olympus_finops_v1_finops_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EstimateCostRequest.ProtoReflect.Descriptor instead.
func (*EstimateCostRequest) Descriptor() ([]byte, []int) {
	return file_olympus_finops_v1_finops_proto_rawDescGZIP(), []int{0}
}

func (x *EstimateCostRequest) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *EstimateCostRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *EstimateCostRequest) GetParameters() map[string]string {
	if x != nil {
		return x.Parameters
	}
	return nil
}

type EstimateCostResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EstimatedUsd  float64                `protobuf:"fixed64,1,opt,name=estimated_usd,json=estimatedUsd,proto3" json:"estimated_usd,omitempty"`
	Confidence    string                 `protobuf:"bytes,2,opt,name=confidence,proto3" json:"confidence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EstimateCostResponse) Reset() {
	*x = EstimateCostResponse{}
	mi := &file_olympus_finops_v1_finops_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EstimateCostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EstimateCostResponse) ProtoMessage() {}

func (x *EstimateCostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_olympus_finops_v1_finops_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EstimateCostResponse.ProtoReflect.Descriptor instead.
func (*EstimateCostResponse) Descriptor() ([]byte, []int) {
	return file_olympus_finops_v1_finops_proto_rawDescGZIP(), []int{1}
}

func (x *EstimateCostResponse) GetEstimatedUsd() float64 {
	if x != nil {
		return x.EstimatedUsd
	}
	return 0
}

func (x *EstimateCostResponse) GetConfidence() string {
	if x != nil {
		return x.Confidence
	}
	return ""
}

type ValidateBudgetRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ProjectId       string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	RequestedAmount float64                `protobuf:"fixed64,2,opt,name=requested_amount,json=requestedAmount,proto3" json:"requested_amount,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ValidateBudgetRequest) Reset() {
	*x = ValidateBudgetRequest{}
	mi := &file_olympus_finops_v1_finops_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateBudgetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateBudgetRequest) ProtoMessage() {}

func (x *ValidateBudgetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_olympus_finops_v1_finops_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateBudgetRequest.ProtoReflect.Descriptor instead.
func (*ValidateBudgetRequest) Descriptor() ([]byte, []int) {
	return file_olympus_finops_v1_finops_proto_rawDescGZIP(), []int{2}
}

func (x *ValidateBudgetRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *ValidateBudgetRequest) GetRequestedAmount() float64 {
	if x != nil {
		return x.RequestedAmount
	}
	return 0
}

type ValidateBudgetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Approved      bool                   `protobuf:"varint,1,opt,name=approved,proto3" json:"approved,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateBudgetResponse) Reset() {
	*x = ValidateBudgetResponse{}
	mi := &file_olympus_finops_v1_finops_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateBudgetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateBudgetResponse) ProtoMessage() {}

func (x *ValidateBudgetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_olympus_finops_v1_finops_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateBudgetResponse.ProtoReflect.Descriptor instead.
func (*ValidateBudgetResponse) Descriptor() ([]byte, []int) {
	return file_olympus_finops_v1_finops_proto_rawDescGZIP(), []int{3}
}

func (x *ValidateBudgetResponse) GetApproved() bool {
	if x != nil {
		return x.Approved
	}
	return false
}

func (x *ValidateBudgetResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_olympus_finops_v1_finops_proto protoreflect.FileDescriptor

const file_olympus_finops_v1_finops_proto_rawDesc = "" +
	"\n" +
	"\x1eolympus/finops/v1/finops.proto\x12\x11olympus.finops.v1\"\xde\x01\n" +
	"\x13EstimateCostRequest\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\x12\x16\n" +
	"\x06action\x18\x02 \x01(\tR\x06action\x12V\n" +
	"\n" +
	"parameters\x18\x03 \x03(\v26.olympus.finops.v1.EstimateCostRequest.ParametersEntryR\n" +
	"parameters\x1a=\n" +
	"\x0fParametersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"[\n" +
	"\x14EstimateCostResponse\x12#\n" +
	"\restimated_usd\x18\x01 \x01(\x01R\festimatedUsd\x12\x1e\n" +
	"\n" +
	"confidence\x18\x02 \x01(\tR\n" +
	"confidence\"a\n" +
	"\x15ValidateBudgetRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12)\n" +
	"\x10requested_amount\x18\x02 \x01(\x01R\x0frequestedAmount\"N\n" +
	"\x16ValidateBudgetResponse\x12\x1a\n" +
	"\bapproved\x18\x01 \x01(\bR\bapproved\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xd7\x01\n" +
	"\rFinOpsService\x12_\n" +
	"\fEstimateCost\x12&.olympus.finops.v1.EstimateCostRequest\x1a'.olympus.finops.v1.EstimateCostResponse\x12e\n" +
	"\x0eValidateBudget\x12(.olympus.finops.v1.ValidateBudgetRequest\x1a).olympus.finops.v1.ValidateBudgetResponseB\xf7\x01\n" +
	"\x15com.olympus.finops.v1B\vFinopsProtoP\x01ZkOlympusGCP-FinOps/40000-Communication-Contracts/430-Protocol-Definitions/000-gen/olympus/finops/v1;finopsv1\xa2\x02\x03OFX\xaa\x02\x11Olympus.Finops.V1\xca\x02\x11Olympus\\Finops\\V1\xe2\x02\x1dOlympus\\Finops\\V1\\GPBMetadata\xea\x02\x13Olympus::Finops::V1b\x06proto3"

var (
	file_olympus_finops_v1_finops_proto_rawDescOnce sync.Once
	file_olympus_finops_v1_finops_proto_rawDescData []byte
)

func file_olympus_finops_v1_finops_proto_rawDescGZIP() []byte {
	file_olympus_finops_v1_finops_proto_rawDescOnce.Do(func() {
		file_olympus_finops_v1_finops_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_olympus_finops_v1_finops_proto_rawDesc), len(file_olympus_finops_v1_finops_proto_rawDesc)))
	})
	return file_olympus_finops_v1_finops_proto_rawDescData
}

var file_olympus_finops_v1_finops_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_olympus_finops_v1_finops_proto_goTypes = []any{
	(*EstimateCostRequest)(nil),    // 0: olympus.finops.v1.EstimateCostRequest
	(*EstimateCostResponse)(nil),   // 1: olympus.finops.v1.EstimateCostResponse
	(*ValidateBudgetRequest)(nil),  // 2: olympus.finops.v1.ValidateBudgetRequest
	(*ValidateBudgetResponse)(nil), // 3: olympus.finops.v1.ValidateBudgetResponse
	nil,                            // 4: olympus.finops.v1.EstimateCostRequest.ParametersEntry
}
var file_olympus_finops_v1_finops_proto_depIdxs = []int32{
	4, // 0: olympus.finops.v1.EstimateCostRequest.parameters:type_name -> olympus.finops.v1.EstimateCostRequest.ParametersEntry
	0, // 1: olympus.finops.v1.FinOpsService.EstimateCost:input_type -> olympus.finops.v1.EstimateCostRequest
	2, // 2: olympus.finops.v1.FinOpsService.ValidateBudget:input_type -> olympus.finops.v1.ValidateBudgetRequest
	1, // 3: olympus.finops.v1.FinOpsService.EstimateCost:output_type -> olympus.finops.v1.EstimateCostResponse
	3, // 4: olympus.finops.v1.FinOpsService.ValidateBudget:output_type -> olympus.finops.v1.ValidateBudgetResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_olympus_finops_v1_finops_proto_init() }
func file_olympus_finops_v1_finops_proto_init() {
	if File_olympus_finops_v1_finops_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_olympus_finops_v1_finops_proto_rawDesc), len(file_olympus_finops_v1_finops_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_olympus_finops_v1_finops_proto_goTypes,
		DependencyIndexes: file_olympus_finops_v1_finops_proto_depIdxs,
		MessageInfos:      file_olympus_finops_v1_finops_proto_msgTypes,
	}.Build()
	File_olympus_finops_v1_finops_proto = out.File
	file_olympus_finops_v1_finops_proto_goTypes = nil
	file_olympus_finops_v1_finops_proto_depIdxs = nil
}
